### ISSUE TITLE
Oracle database ORA-00904: "U"."COMMON": invalid identifier 

### ISSUE THREAD

**Issue by xYx-c** [kndndrj/nvim-dbee#33]
Will Oracle database be supported in the future?

**Comment by kndndrj** [comment]
@xYx-c 
The support is there, however Oracle is very hard to work with due to multiple different edge cases and various weird problems. I tested the driver with the free version of oracle and it seemed to work fine.

However it is totaly possible that the version you are tryinv to use is for some reason not supported, or it might have some special DSN (I'm not sure where the error from the title comes from).

I'll try to look into this at some point, but for now the besg i can do is point you to go-ora docs, which might contain something useful for you.

Let me know if you find anything.

**Comment by xYx-c** [comment]
#### Oracle19c
Is there any way I can see the run log?
``` json
{
    "id": "__master_connection_id_manageroracle__",
    "page_size": 20, "name": "dbname", 
    "type": "oracle", 
    "url": "oracle://dbname:pwd@10.8.xxx.xxx:1521/orcl"
}
```
#### configuration information
``` lua
require("dbee").setup({
    sources = {
        require("dbee.sources").MemorySource:new({
            -- {
            --     name = "postgres",
            --     type = "postgres",
            --     url = "postgres://root:root@172.18.0.10/postgres?sslmode=disable",
            -- },
        }),
        require("dbee.sources").EnvSource:new("DBEE_CONNECTIONS"),
        require("dbee.sources").FileSource:new(vim.fn.stdpath("cache") .. "/dbee/persistence.json"),
    },
    editor = {
        mappings = {
            run_selection = { key = "<CR>", mode = "v" },
            run_file = { key = "BB", mode = "n" },
        },
    },
})
```

**Comment by kndndrj** [comment]
You can cat or tail this file: `~/.cache/nvim/dbee/dbee.log` ( not 100% sure - writing from my phone, but it should be here somewhere)

If you have a docker image that I could use to run this version of oracle, I might be able to help.
