### ISSUE TITLE
[Bug] Doc issue; Duplicate "DefaultLayout"

### ISSUE THREAD

**Issue by TroySigX** [kndndrj/nvim-dbee#72]
I encountered this error while trying to install the plugin:
```
...hare/nvim/lazy/lazy.nvim/lua/lazy/manage/task/plugin.lua:84: Vim:E154: Duplicate tag "DefaultLayout" in file /home/troysigx/.local/share/nvim/lazy/nvim-dbee/doc//dbee-reference.txt

```

**Comment by RunningIkkyu** [comment]
I got the same error

**Comment by RunningIkkyu** [comment]
It turns out the docs has duplicated defination:

https://github.com/kndndrj/nvim-dbee/blob/2f8e14e8dcd397f5da45fcd73d9576692906a4e3/doc/dbee-reference.txt#L455

A PR https://github.com/kndndrj/nvim-dbee/pull/95 has been created to fix this issue. 

For anyone who need to fix this before the PR merged, use `RunningIkkyu/nvim-dbee` instead (remember to change back after PR merged)

```
return {
  -- "kndndrj/nvim-dbee",
  "RunningIkkyu/nvim-dbee",
  dependencies = {
    "MunifTanjim/nui.nvim",
  },
  build = function()
    -- Install tries to automatically detect the install method.
    -- if it fails, try calling it with one of these parameters:
    --    "curl", "wget", "bitsadmin", "go"
    require("dbee").install()
  end,
  config = function()
    require("dbee").setup(--[[optional config]])
  end,
}
```

**Comment by nobleach** [comment]
I'm still seeing this. I've tried pulling the plugin and cleaning up. Even on new install it fails with this.
